---
language: c
install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq bash cmake libssl-dev maven ruby ruby-dev
    python python-dev php5 openjdk-7-jdk swig uuid-dev valgrind libsasl2-dev
    sasl2-bin
- gem install rspec simplecov
script:
- bin/jenkins-proton-c-build.sh
os:
- linux
