version: '{branch}.{build}'
configuration: RelWithDebInfo
install:
- cinst -y swig
before_build:
- mkdir BLD
- cd BLD
- cmake -G "Visual Studio 12" -DBUILD_PERL=no ..
- cd ..
build:
  parallel: true
  verbosity: normal
test_script:
- cd BLD
- cmake --build . --target install --config %CONFIGURATION%
- ctest -V -C %CONFIGURATION%
- cd ..
